CREATE TABLE PERSON(
    ID INT DEFAULT NEXTVAL('PERSON_ID_SEQ') PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL, 
    LAST_NAME VARCHAR(15) NOT NULL, 
    MIDDLE_NAME VARCHAR(15), 
    STREET VARCHAR(50), 
    BRGY VARCHAR(20),
    CITY VARCHAR(20),
    ZIP INT,
    BIRTH_DATE DATE NOT NULL,
    GWA FLOAT8,
    DATE_HIRED DATE,
    EMPLOYED BOOLEAN, 
    TITLE VARCHAR(10) NOT NULL
);

CREATE TABLE ROLE(
    ROLE_ID INT DEFAULT NEXTVAL('ROLE_ID_SEQ') PRIMARY KEY NOT NULL,
    ROLE_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE PERSON_ROLES(
    PERSON_ID INT REFERENCES PERSON(ID) ON DELETE CASCADE NOT NULL, 
    ROLE_ROLE_ID INT REFERENCES ROLE(ROLE_ID) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE CONTACT(
    PERSON_ID INT REFERENCES PERSON(ID) ON DELETE CASCADE NOT NULL,  
    CONTACT_ID INT DEFAULT NEXTVAL('CONTACT_SEQ') PRIMARY KEY NOT NULL,
    CONTACT_TYPE VARCHAR(10) NOT NULL, 
    CONTACT_DETAILS VARCHAR(20),
    UNIQUE (PERSON_ID, CONTACT_TYPE, CONTACT_DETAILS)
);

GRANT ALL PRIVILEGES ON TABLE ROLE TO ecc;
GRANT ALL PRIVILEGES ON TABLE CONTACT TO ecc;
GRANT ALL PRIVILEGES ON TABLE PERSON TO ecc;
GRANT ALL PRIVILEGES ON TABLE PERSON_ROLES TO ecc;

--ADD INDEX
CREATE UNIQUE INDEX ROLE_NAME_IDX ON ROLE(ROLE_NAME); 

--ADD CONSTRAINTS
ALTER TABLE PERSON_ROLES ADD CONSTRAINT FK_PERSON_ROLE UNIQUE (ROLE_ROLE_ID, PERSON_ID);
