ALTER SEQUENCE PERSON_ID_SEQ RESTART WITH 1;
ALTER SEQUENCE ROLE_ID_SEQ RESTART WITH 1;
ALTER SEQUENCE CONTACT_SEQ RESTART WITH 1;

DELETE FROM PERSON;
DELETE FROM ROLE;

SELECT * FROM PERSON_ROLES;
SELECT * FROM PERSON;
SELECT * FROM ROLE;
SELECT * FROM CONTACT;
