CREATE USER ecc PASSWORD 'ex1stgl0bal';

CREATE DATABASE HR;
GRANT ALL PRIVILEGES ON DATABASE HR TO ecc;

/*in HR DATABASE*/
--SEQUENCES
CREATE SEQUENCE PERSON_ID_SEQ;
CREATE SEQUENCE ROLE_ID_SEQ;
CREATE SEQUENCE CONTACT_SEQ;

GRANT ALL PRIVILEGES ON SEQUENCE PERSON_ID_SEQ TO ecc;
GRANT ALL PRIVILEGES ON SEQUENCE ROLE_ID_SEQ TO ecc;
GRANT ALL PRIVILEGES ON SEQUENCE CONTACT_SEQ TO ecc;


